# Site settings
title: Ionel Hosu blog
email: 
description: "Thoughts of a Machine Learning Researcher."
baseurl: ""
url: "http://ionelhosu.github.io"
twitter_username: ionelhosu
github_username:  ionelhosu

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
